version: "2"

services:

  flask:
    build:
      context: flask
    volumes:
    - ./config.py:/app/config.py
    - ./financial.py:/app/financial.py
    ports:
    - 5000:5000
    
  ngrok:
    image: wernight/ngrok
    environment:
    - NGROK_PORT=flask:5000
    - NGROK_AUTH=41AMeDMuYST8Q2qDxRqxD_7e6CTLjJTFbuys13oqhKw
    depends_on:
    - flask
    
    

